=== MChaparroCaballero/ACESSO_A_DATOS/EsquemaXml/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">

    <complexType name="Videojuego">
    	<sequence>
    		<element name="Desarrollador" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Plataforma" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="Género" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="AñodeLanzamiento" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="ClasificaciónPorEdades" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="NumeroDeCopiasDisponibles" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="Titulo" type="string"></attribute>
    </complexType>

    <complexType name="Videojuegos">
    	<sequence>
    		<element name="videojuego" type="tns:Videojuego" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>


    <element name="ColeccionVideojuegos" type="tns:Videojuegos"></element>
</schema>

=== MChaparroCaballero/ACESSO_A_DATOS/EsquemaXml/NewXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ColeccionVideojuegos xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd ">
	<tns:videojuego Titulo="Call of duty">
		<tns:Desarrollador>Infinity ward</tns:Desarrollador>
		<tns:Plataforma>Playstation 4</tns:Plataforma>
		<tns:Género>belico</tns:Género>
		<tns:AñodeLanzamiento>2003</tns:AñodeLanzamiento>
		<tns:ClasificaciónPorEdades>PEGI 18</tns:ClasificaciónPorEdades>
		<tns:NumeroDeCopiasDisponibles>50</tns:NumeroDeCopiasDisponibles>
	</tns:videojuego>
	<tns:videojuego Titulo="Five night at Freddys">
		<tns:Desarrollador> Scottgames</tns:Desarrollador>
		<tns:Plataforma>PC</tns:Plataforma>
		<tns:Género>Survival horror</tns:Género>
		<tns:AñodeLanzamiento>2014</tns:AñodeLanzamiento>
		<tns:ClasificaciónPorEdades>PG-13</tns:ClasificaciónPorEdades>
		<tns:NumeroDeCopiasDisponibles>100</tns:NumeroDeCopiasDisponibles>
	</tns:videojuego>
	<tns:videojuego Titulo="Los sims 4">
		<tns:Desarrollador>Maxis</tns:Desarrollador>
		<tns:Plataforma>pc</tns:Plataforma>
		<tns:Género>Simulacion de vida</tns:Género>
		<tns:AñodeLanzamiento>2014</tns:AñodeLanzamiento>
		<tns:ClasificaciónPorEdades>PEGI 12</tns:ClasificaciónPorEdades>
		<tns:NumeroDeCopiasDisponibles>75</tns:NumeroDeCopiasDisponibles>
	</tns:videojuego>
	<tns:videojuego Titulo="Genshin impact">
		<tns:Desarrollador>miHoyo</tns:Desarrollador>
		<tns:Plataforma>PC</tns:Plataforma>
		<tns:Género>Aventura</tns:Género>
		<tns:AñodeLanzamiento>2020</tns:AñodeLanzamiento>
		<tns:ClasificaciónPorEdades>ESRB PEGI CERO</tns:ClasificaciónPorEdades>
		<tns:NumeroDeCopiasDisponibles>69</tns:NumeroDeCopiasDisponibles>
	</tns:videojuego>
	<tns:videojuego Titulo="Assasin's creed odyssey">
		<tns:Desarrollador>Ubisoft</tns:Desarrollador>
		<tns:Plataforma>PC</tns:Plataforma>
		<tns:Género>Acción y aventura</tns:Género>
		<tns:AñodeLanzamiento>2018</tns:AñodeLanzamiento>
		<tns:ClasificaciónPorEdades>PEGI 18</tns:ClasificaciónPorEdades>
		<tns:NumeroDeCopiasDisponibles>55</tns:NumeroDeCopiasDisponibles>
	</tns:videojuego></tns:ColeccionVideojuegos>
